/**
 * PROJECT:         ExectOS
 * COPYRIGHT:       See COPYING.md in the top level directory
 * FILE:            includes/cmake/version/xtver.h.cmake
 * DESCRIPTION:     XT version information - generated by toolchain
 * DEVELOPERS:      Rafal Kupiec <belliash@codingworkshop.eu.org>
 */

#ifndef __XTGEN_XTVER_H
#define __XTGEN_XTVER_H

#define XTOS_VERSION                     "@XTOS_VERSION_MAJOR@.@XTOS_VERSION_MINOR@-@XTOS_VERSION_BUILD@"
#define XTOS_VERSION_MAJOR               @XTOS_VERSION_MAJOR@
#define XTOS_VERSION_MINOR               @XTOS_VERSION_MINOR@
#define XTOS_VERSION_BUILD               "@XTOS_VERSION_BUILD@"
#define XTOS_VERSION_HASH                "@XTOS_VERSION_HASH@"

#define XTOS_VERSION_ARCH                "@ARCH@"
#define XTOS_VERSION_DATE                "@XTOS_VERSION_DATE@"
#define XTOS_VERSION_FULLDATE            "@XTOS_VERSION_FULLDATE@"
#define XTOS_VERSION_YEAR                "@XTOS_VERSION_YEAR@"

#define XTOS_COMPATIBLE_MAJOR            @XTOS_COMPATIBLE_MAJOR@
#define XTOS_COMPATIBLE_MINOR            @XTOS_COMPATIBLE_MINOR@
#define XTOS_COMPATIBLE_BUILD            @XTOS_COMPATIBLE_BUILD@
#define XTOS_COMPATIBLE_VERSION          @XTOS_COMPATIBLE_VERSION@
#define XTOS_COMPATIBLE_VERSION_BUILD    @XTOS_COMPATIBLE_VERSION@@XTOS_COMPATIBLE_BUILD@

#define XTOS_COMPILER_NAME               "@CMAKE_C_COMPILER_ID@"
#define XTOS_COMPILER_VERSION            "@CMAKE_C_COMPILER_VERSION@"

#define XTLDR_VERSION_MAJOR              @XTLDR_VERSION_MAJOR@
#define XTLDR_VERSION_MINOR              @XTLDR_VERSION_MINOR@

#endif /* __XTGEN_XTVER_H */
