# XTOS kernel exports
@ fastcall ExAcquireRundownProtection(ptr)
@ fastcall ExCompleteRundownProtection(ptr)
@ fastcall ExInitializeRundownProtection(ptr)
@ fastcall ExReInitializeRundownProtection(ptr)
@ fastcall ExReleaseRundownProtection(ptr)
@ fastcall ExWaitForRundownProtectionRelease(ptr)
@ cdecl HlReadPort8(ptr)
@ cdecl HlReadPort16(ptr)
@ cdecl HlReadPort32(ptr)
@ stdcall HlReadRegister8(ptr)
@ stdcall HlReadRegister16(ptr)
@ stdcall HlReadRegister32(ptr)
@ cdecl HlWritePort8(ptr long)
@ cdecl HlWritePort16(ptr long)
@ cdecl HlWritePort32(ptr long)
@ stdcall HlWriteRegister8(ptr long)
@ stdcall HlWriteRegister16(ptr long)
@ stdcall HlWriteRegister32(ptr long)
@ fastcall KeAcquireQueuedSpinLock(long)
@ fastcall KeAcquireSpinLock(ptr)
@ stdcall KeAcquireSystemResource(long ptr)
@ stdcall KeCancelTimer(ptr)
@ fastcall KeGetCurrentRunLevel()
@ stdcall KeGetTimerState(ptr)
@ stdcall KeGetSystemResource(long ptr)
@ stdcall KeInitializeApc(ptr ptr long ptr ptr ptr long ptr)
@ stdcall KeInitializeDpc(ptr ptr ptr)
@ stdcall KeInitializeSemaphore(ptr long long)
@ stdcall KeInitializeSpinLock(ptr)
@ stdcall KeInitializeThreadedDpc(ptr ptr ptr)
@ stdcall KeInitializeTimer(ptr long)
@ fastcall KeLowerRunLevel(long)
@ fastcall KeRaiseRunLevel(long)
@ stdcall KeReadSemaphoreState(ptr)
@ stdcall KeReleaseSemaphore(ptr long long long)
@ fastcall KeReleaseQueuedSpinLock(long)
@ fastcall KeReleaseSpinLock(ptr)
@ stdcall KeReleaseSystemResource(ptr)
@ stdcall KeSetTargetProcessorDpc(ptr long)
@ stdcall KeSetTimer(ptr long long long ptr)
@ stdcall KeSignalCallDpcDone(ptr)
@ stdcall KeSignalCallDpcSynchronize(ptr)
@ stdcall RtlClearAllBits(ptr)
@ stdcall RtlClearBit(ptr long)
@ stdcall RtlClearBits(ptr long long)
@ stdcall RtlClearSetBits(ptr long long)
@ stdcall RtlCompareGuids(ptr ptr)
@ stdcall RtlCompareMemory(ptr ptr long)
@ stdcall RtlCompareString(str str long)
@ stdcall RtlCompareStringInsensitive(str str long)
@ stdcall RtlCompareWideString(wstr wstr long)
@ stdcall RtlCompareWideStringInsensitive(wstr wstr long)
@ stdcall RtlConcatenateString(str str long)
@ stdcall RtlConcatenateWideString(wstr wstr long)
@ stdcall RtlConvertToLargeInteger32(long)
@ stdcall RtlConvertToLargeIntegerUnsigned32(long)
@ stdcall RtlCopyMemory(ptr ptr long)
@ stdcall RtlCopyString(ptr ptr long)
@ stdcall RtlCopyWideString(ptr ptr long)
@ stdcall RtlDivideLargeInteger(long long long ptr)
@ stdcall RtlFindClearBits(ptr long long)
@ stdcall RtlFindSetBits(ptr long long)
@ stdcall RtlFindString(str str)
@ stdcall RtlFindStringInsensitive(str str)
@ stdcall RtlFindWideString(wstr wstr)
@ stdcall RtlFindWideStringInsensitive(wstr wstr)
@ stdcall RtlInitializeBitMap(ptr ptr long)
@ stdcall RtlInitializeListHead(ptr)
@ stdcall RtlInsertHeadList(ptr ptr)
@ stdcall RtlInsertTailList(ptr ptr)
@ stdcall RtlListEmpty(ptr)
@ stdcall RtlListLoop(ptr)
@ stdcall RtlMoveMemory(ptr ptr long)
@ stdcall RtlMultiplyLargeInteger(long long long)
@ stdcall RtlRemoveEntryList(ptr)
@ stdcall RtlReverseString(str long)
@ stdcall RtlReverseWideString(wstr long)
@ stdcall RtlSameMemory(ptr ptr long)
@ stdcall RtlSetAllBits(ptr)
@ stdcall RtlSetBit(ptr long)
@ stdcall RtlSetBits(ptr long long)
@ stdcall RtlSetClearBits(ptr long long)
@ stdcall RtlSetMemory(ptr long long)
@ stdcall RtlStringLength(str long)
@ stdcall RtlStringToWideString(wstr str long)
@ stdcall RtlTestBit(ptr long)
@ stdcall RtlTokenizeString(str str str)
@ stdcall RtlTokenizeWideString(wstr wstr wstr)
@ stdcall RtlToLowerCharacter(long)
@ stdcall RtlToLowerWideCharacter(long)
@ stdcall RtlToUpperCharacter(long)
@ stdcall RtlToUpperWideCharacter(long)
@ stdcall RtlTrimLeftString(str)
@ stdcall RtlTrimLeftWideString(wstr)
@ stdcall RtlTrimRightString(str)
@ stdcall RtlTrimRightWideString(wstr)
@ stdcall RtlTrimString(str)
@ stdcall RtlTrimWideString(wstr)
@ stdcall RtlWideStringLength(wstr long)
@ stdcall RtlZeroMemory(ptr long)
